### ISSUE TITLE
draft-ietf-jmap-mail: Permissions to perform different mailbox related operations

### ISSUE THREAD

**Issue by aamelnikov** [jmapio/jmap#68] opened 2017-05-01 12:04 UTC
In Section 2:
  o  *mayReadItems*: "Boolean" If true, may use this mailbox as part of
      a filter in a _getMessageList_ call.  If a submailbox is shared
      but not the parent mailbox, this may be "false".

   o  *mayAddItems*: "Boolean" The user may add messages to this mailbox
      (by either creating a new message or moving an existing one).

   o  *mayRemoveItems*: "Boolean" The user may remove messages from this
      mailbox (by either changing the mailboxes of a message or deleting
      it).

   o  *mayCreateChild*: "Boolean" The user may create a mailbox with
      this mailbox as its parent.

   o  *mayRename*: "Boolean" The user may rename the mailbox or make it
      a child of another mailbox.

   o  *mayDelete*: "Boolean" The user may delete the mailbox itself.

Should this reference IMAP ACL RFC (RFC 4314)?

This might be an issue to be mentioned in the JMAP/IMAP co-existence document.

**Comment by neilj** [comment] 2017-09-04 03:37
Closing as a duplicate of #126 which has more comments.

**Closed by neilj** 2017-09-04 03:37 UTC
